[package]
name = "mirco"
version = "0.1.0"
authors = ["Bastian Kauschke <bastian_kauschke@hotmail.de>"]
edition = "2018"

[[bin]]
name = "mirco"
path = "src/main.rs"
test = false
doctest = false
bench = false