[package]
name = "parse"
version = "0.1.0"
authors = ["lcnr/Bastian Kauschke <bastian_kauschke@hotmail.de>"]
edition = "2018"

[dependencies]
boulder_core = { path =  "../boulder_core" }
hir = { path = "../hir" }

[features]
scope = []