[package]
name = "hir"
version = "0.1.0"
authors = ["lcnr/Bastian Kauschke <bastian_kauschke@hotmail.de>"]
edition = "2018"

[dependencies]
tindex = { git = "https://github.com/lcnr/tindex.git" }
solver = { path = "../solver" }
diagnostics = { path = "../diagnostics" }
mir = { path = "../mir" }
